version: '3'

services:
  backend:
    image: registry.cn-heyuan.aliyuncs.com/richard-dev/book-manage-backend:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/book_management?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: richard
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3


  frontend:
    image: registry.cn-heyuan.aliyuncs.com/richard-dev/book-manage-frontend:1.0
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: book_management
      MYSQL_USER: richard
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./custom-my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.108.0.0/16
